#!/bin/bash
#
# Install pre-commit hook to auto-update SUMMARY.md
#
# This script creates a git pre-commit hook that automatically updates SUMMARY.md
# with new markdown files from research/ and output/ directories before each commit.
#
# Usage:
#   bash .claude/hooks/install-hook.sh

set -e

# Color output for better visibility
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}Installing SUMMARY.md auto-update hook...${NC}\n"

# Get repository root
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
if [ $? -ne 0 ]; then
    echo -e "${RED}Error: Not in a git repository${NC}"
    exit 1
fi

HOOK_SCRIPT="$REPO_ROOT/.claude/hooks/update-summary.py"
HOOK_DEST="$REPO_ROOT/.git/hooks/pre-commit"

# Check if Python 3 is available
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error: python3 is required but not found${NC}"
    echo "Please install Python 3 and try again"
    exit 1
fi

echo -e "${GREEN}✓${NC} Python 3 found: $(python3 --version)"

# Check if hook script exists
if [ ! -f "$HOOK_SCRIPT" ]; then
    echo -e "${RED}Error: $HOOK_SCRIPT not found${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} Hook script found"

# Warn if pre-commit hook already exists
if [ -f "$HOOK_DEST" ]; then
    echo -e "${YELLOW}Warning: Pre-commit hook already exists at $HOOK_DEST${NC}"
    echo "The existing hook will be backed up to $HOOK_DEST.backup"
    cp "$HOOK_DEST" "$HOOK_DEST.backup"
    echo -e "${GREEN}✓${NC} Existing hook backed up"
fi

# Create pre-commit hook
cat > "$HOOK_DEST" << 'EOF'
#!/bin/sh
#
# Auto-update SUMMARY.md with research and output files
# Generated by .claude/hooks/install-hook.sh
#

REPO_ROOT=$(git rev-parse --show-toplevel)
HOOK_SCRIPT="$REPO_ROOT/.claude/hooks/update-summary.py"

# Run the update script
if ! python3 "$HOOK_SCRIPT"; then
    echo "Error: Failed to update SUMMARY.md"
    exit 1
fi

# Check if SUMMARY.md was modified
if ! git diff --quiet SUMMARY.md 2>/dev/null; then
    echo "✓ SUMMARY.md updated with new research/output files"
    git add SUMMARY.md
fi

exit 0
EOF

# Make hook executable
chmod +x "$HOOK_DEST"

echo -e "${GREEN}✓${NC} Pre-commit hook installed successfully"
echo ""
echo -e "${GREEN}Installation complete!${NC}"
echo ""
echo "The hook will automatically:"
echo "  1. Scan research/ and output/ directories before each commit"
echo "  2. Update SUMMARY.md with any new .md files"
echo "  3. Stage SUMMARY.md for commit if modified"
echo ""
echo "To test the hook manually, run:"
echo "  ${YELLOW}python3 .claude/hooks/update-summary.py${NC}"
echo ""
echo "To see what would be added without making changes:"
echo "  ${YELLOW}python3 .claude/hooks/update-summary.py --dry-run${NC}"
echo ""
echo "To uninstall the hook:"
echo "  ${YELLOW}rm .git/hooks/pre-commit${NC}"
